package com.vme.precast.bankaccount.api;

import coliseum.service.ColiseumInterface;

public interface BankAccountComponent extends ColiseumInterface {

	public BankAccountServiceResponse createBankAccount(BankAccountServiceRequest bankAccountServiceRequest);

	public BankAccountServiceResponse getBankAccounts(BankAccountServiceRequest bankAccountServiceRequest);

	public BankAccountServiceResponse setDefaultBankAccount(BankAccountServiceRequest bankAccountServiceRequest);

	public BankAccountServiceResponse updateBankAccount(BankAccountServiceRequest bankAccountServiceRequest);

	public BankAccountServiceResponse deleteBankAccount(BankAccountServiceRequest bankAccountServiceRequest);
}
