package com.vme.precast.purchaseorder.api;

import coliseum.service.ColiseumInterface;

public interface PurchaseOrderComponent extends ColiseumInterface {

 public PurchaseOrderServiceResponse createProject(PurchaseOrderServiceRequest purchaseOrderServiceRequest);

 public PurchaseOrderServiceResponse getProjects(PurchaseOrderServiceRequest purchaseOrderServiceRequest);

 public PurchaseOrderServiceResponse updateProject(PurchaseOrderServiceRequest purchaseOrderServiceRequest);

 public PurchaseOrderServiceResponse deleteProject(PurchaseOrderServiceRequest purchaseOrderServiceRequest);
}
