package com.vme.precast.castingactivity.api;

public interface CastingActivityService {

	public CastingActivityServiceResponse createCastingActivity(CastingActivityServiceRequest serviceRequest);

	public CastingActivityServiceResponse getCastingActivitys(CastingActivityServiceRequest serviceRequest);

	public CastingActivityServiceResponse updateCastingActivity(CastingActivityServiceRequest serviceRequest);

	public CastingActivityServiceResponse deleteCastingActivity(CastingActivityServiceRequest serviceRequest);
}
