package com.vme.precast.itemfreightamountdetails.api;

import coliseum.service.ColiseumInterface;

public interface ItemFreightAmountDetailsComponent extends ColiseumInterface {

 public ItemFreightAmountDetailsServiceResponse createItemFreightAmountDetails(ItemFreightAmountDetailsServiceRequest itemFreightAmountDetailsServiceRequest);

 public ItemFreightAmountDetailsServiceResponse getItemFreightAmountDetailss(ItemFreightAmountDetailsServiceRequest itemFreightAmountDetailsServiceRequest);

 public ItemFreightAmountDetailsServiceResponse updateItemFreightAmountDetails(ItemFreightAmountDetailsServiceRequest itemFreightAmountDetailsServiceRequest);

 public ItemFreightAmountDetailsServiceResponse deleteItemFreightAmountDetails(ItemFreightAmountDetailsServiceRequest itemFreightAmountDetailsServiceRequest);
}
